Repository egghit/gammeokda, pull requests merged in 2023-02, with the labels that each got.

#1 Setting/init: 프로젝트 셋업
  .eslintrc
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/setting.md
  .github/ISSUE_TEMPLATE/style.md
  .github/ISSUE_TEMPLATE/test.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .husky/pre-commit
  .huskyrc
  .prettierrc
  index.html
  package.json
  public/favicon.svg
  src/@types/.gitkeep
  src/App.tsx
  src/apis/.gitkeep
  src/assets/.gitkeep
  src/components/.gitkeep
  src/components/CalendarPage/Calendar/index.tsx
  src/components/CreatePage/.gitkeep
  src/components/ListPage/.gitkeep
  src/components/LoginPage/.gitkeep
  src/components/MainPage/.gitkeep
  src/components/SettingPage/.gitkeep
  src/components/common/.gitkeep
  src/config/index.ts
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/main.tsx
  src/pages/.gitkeep
  src/routes/index.tsx
  src/store/.gitkeep
  src/styles/reset.ts
  src/styles/theme.ts
  src/utils/.gitkeep
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  tsconfig.path.json
  vite.config.ts
  yarn.lock
Labels: ⚙️ setting

#6 Feat/firebase
  .firebaserc
  .gitignore
  firebase.json
  firestore.indexes.json
  firestore.rules
  package.json
  src/@types/types.d.ts
  src/App.tsx
  src/config/index.ts
  src/firebase.ts
  src/pages/Test.tsx
  storage.rules
  yarn.lock
Labels: ✨ feat

#8 Feat/write layout : theme 추가, 폰트변경, 기분 선택가능
  public/fonts/DNFBitBitTTF.ttf
  src/App.tsx
  src/components/DiaryWritePage/WriteWapper.tsx
  src/components/MainPage/.gitkeep
  src/pages/DiaryWritePage.tsx
  src/styles/reset.ts
  src/styles/theme.ts
Labels: ✨ feat

#10 Fix/theme-bug: ThemeProvider 코드 수정
  src/App.tsx
Labels: 🛠 fix

#9 Feat/common modal
  public/close_icon.svg
  public/우는얼굴.svg
  src/components/DiaryListPage/Diary/Diary.tsx
  src/components/common/.gitkeep
  src/components/common/Modal.style.tsx
  src/components/common/Modal.tsx
  src/pages/Test.tsx
Labels: ✨ feat

#16 [feat] diary style
  src/@types/types.d.ts
  src/assets/.gitkeep
  src/assets/background.png
  src/assets/commonIcon/arrow_down.svg
  src/assets/commonIcon/arrow_left.svg
  src/assets/commonIcon/arrow_right.svg
  src/assets/commonIcon/arrow_sort.svg
  src/assets/commonIcon/arrow_up.svg
  src/assets/commonIcon/cancel_round.svg
  src/assets/commonIcon/delete_trash.svg
  src/assets/commonIcon/edit_pencil.svg
  src/assets/commonIcon/index.tsx
  src/assets/commonIcon/plus_round.svg
  src/assets/emotionIcon/angry_active.svg
  src/assets/emotionIcon/delight_active.svg
  src/assets/emotionIcon/happy_active.svg
  src/assets/emotionIcon/index.tsx
  src/assets/emotionIcon/sad_active.svg
  src/assets/emotionIcon/soso_active.svg
  src/components/DiaryListPage/Diary/Diary.style.tsx
  src/components/DiaryListPage/Diary/Diary.tsx
  src/components/DiaryListPage/DiaryListPage.style.ts
  src/icon.d.ts
  src/pages/DiaryListPage.tsx
  src/pages/Test.tsx
  src/styles/reset.ts
  vite.config.ts
Labels: ✨ feat

#7 Feat/firebase-functions: Firebase functions 추가
  functions/.firebaserc
  functions/.gitignore
  functions/firebase.json
  functions/package.json
  functions/src/apis/auth/index.ts
  functions/src/apis/diary/index.ts
  functions/src/apis/diary/service.ts
  functions/src/apis/tamagotchi/index.ts
  functions/src/config/index.ts
  functions/src/firebase/admin.ts
  functions/src/firebase/db.ts
  functions/src/index.ts
  functions/tsconfig.json
  functions/yarn.lock
Labels: ✨ feat

#18 Feat/calendar: 캘린더 페이지 기능 및 마크업
  package.json
  src/App.tsx
  src/assets/emotionIcon/angry_active.svg
  src/assets/emotionIcon/delight_active.svg
  src/assets/emotionIcon/happy_active.svg
  src/assets/emotionIcon/sad_active.svg
  src/assets/emotionIcon/soso_active.svg
  src/components/CalendarPage/Calendar/index.tsx
  src/components/CalendarPage/CalendarDiaryList.style.ts
  src/components/CalendarPage/CalendarDiaryList.tsx
  src/components/CalendarPage/CalendarPage.style.ts
  src/components/CalendarPage/CalendarTileContent.style.ts.tsx
  src/components/CalendarPage/CalendarTileContent.tsx
  src/components/CalendarPage/CalendarTileModal.style.ts
  src/components/CalendarPage/CalendarTileModal.tsx
  src/components/CalendarPage/CalendarWrapper.style.ts
  src/components/CalendarPage/CalendarWrapper.tsx
  src/components/DiaryWritePage/WriteWapper.tsx
  src/pages/CalendarPage.tsx
  src/styles/override.css
  src/utils/date.ts
  src/utils/emotion.ts
  yarn.lock
Labels: ✨ feat

#17 Feat/write-layout: 일기 쓰기 페이지 마크업
  src/App.tsx
  src/assets/Button.svg
  src/assets/SpeechBubble.svg
  src/assets/background.png
  src/assets/emotionIcon/angry_active.svg
  src/assets/emotionIcon/angry_disabled.svg
  src/assets/emotionIcon/delight_active.svg
  src/assets/emotionIcon/delight_disabled.svg
  src/assets/emotionIcon/happy_active.svg
  src/assets/emotionIcon/happy_disabled.svg
  src/assets/emotionIcon/index.tsx
  src/assets/emotionIcon/sad_active.svg
  src/assets/emotionIcon/sad_disabled.svg
  src/assets/emotionIcon/soso_active.svg
  src/assets/emotionIcon/soso_disabled.svg
  src/components/.gitkeep
  src/components/CreatePage/.gitkeep
  src/components/DiaryWritePage/DamagochiGreeting/DamagochiGreeting.style.ts
  src/components/DiaryWritePage/DamagochiGreeting/index.tsx
  src/components/DiaryWritePage/DiaryForm/DiaryForm.style.ts
  src/components/DiaryWritePage/DiaryForm/index.tsx
  src/components/DiaryWritePage/EmotionIcon.tsx
  src/components/DiaryWritePage/WriteWapper.tsx
  src/components/common/Button/Button.style.ts
  src/components/common/Button/index.tsx
  src/pages/DiaryWritePage.tsx
  src/styles/reset.ts
Labels: ✨ feat

#21 [feat] Add Change emotion image
  src/components/DiaryListPage/Diary/Diary.style.tsx
  src/components/DiaryListPage/Diary/Diary.tsx
  src/pages/DiaryListPage.tsx
Labels: ✨ feat

#22 Feat/application-entry: 로그인과 이름 짓기 페이지 마크업
  index.html
  public/favicon.png
  public/favicon.svg
  src/@types/react-app-env.d.ts
  src/App.tsx
  src/assets/damagochi.svg
  src/assets/damagochi_egg.svg
  src/assets/kakao_login_button.png
  src/assets/logo.png
  src/components/DiaryWritePage/EmotionIcon.tsx
  src/components/LoginPage/.gitkeep
  src/components/SigninPage/SigninButton/SigninButton.style.tsx
  src/components/SigninPage/SigninButton/index.tsx
  src/components/SignupPage/NamingForm/NamingForm.style.ts
  src/components/SignupPage/NamingForm/index.tsx
  src/components/common/Button/Button.style.ts
  src/components/common/Button/index.tsx
  src/config/index.ts
  src/pages/OAuthPage.tsx
  src/pages/SigninPage.tsx
  src/pages/SignupPage.tsx
Labels: ✨ feat

#25 Feat/post-diary: 일기 작성 페이지 기능 구현
  src/components/DiaryWritePage/DamagochiGreeting/DamagochiGreeting.style.ts
  src/components/DiaryWritePage/DamagochiGreeting/index.tsx
  src/components/DiaryWritePage/DiaryForm/DiaryForm.style.ts
  src/components/DiaryWritePage/DiaryForm/index.tsx
  src/components/DiaryWritePage/GobackButton/GobackButton.style.ts
  src/components/DiaryWritePage/GobackButton/index.tsx
  src/pages/DiaryWritePage.tsx
Labels: ✨ feat

#27 Refactor: SettingPage, Modal 컴포넌트 스타일 수정 및 리팩토링
  src/assets/commonIcon/close.svg
  src/components/SettingPage/Setting.style.tsx
  src/components/SettingPage/Setting.tsx
  src/components/common/Modal/Modal.style.tsx
  src/components/common/Modal/index.tsx
  src/pages/SettingPage.tsx
  src/pages/index.style.ts
Labels: 🧑‍🔧 refactor

#38 Feat/write
  index.html
  package-lock.json
  public/log200.png
  src/assets/background.png
  src/components/DiaryWritePage/DamagochiGreeting/DamagochiGreeting.style.ts
  src/components/DiaryWritePage/DamagochiGreeting/index.tsx
  yarn.lock
Labels: ✨ feat

#35 Feat/polish-css: CSS 최종 수정 작업
  index.html
  src/App.tsx
  src/components/DiaryWritePage/DiaryForm/DiaryForm.style.ts
  src/components/MainPage/Damagochi/damagochi.styels.ts
  src/components/common/GNB/GNB.styles.ts
  src/pages/DesktopPage.tsx
  src/pages/Layout.tsx
  src/pages/index.style.ts
  src/routes/index.tsx
Labels: ✨ feat
